- buildSrc/version.properties
将havenask镜像版本升级到0.3.0。
havanask发布了0.3.0版本，具体介绍见：https://github.com/alibaba/havenask/wiki/havenask:0.3.0
> 将havenask镜像版本升级到0.3.0

- modules/havenask-engine/config/havenask/script/general_search_starter.py
- modules/havenask-engine/src/main/java/org/havenask/engine/NativeProcessControlService.java
启动searcher、qrs时指定tcp端口。
之前不指定searcher tcp端口，searcher重启后，会使用新的port，导致qrs无法访问，指定searcher tcp端口后，可以解决该问题。
> 启动searcher、qrs时指定tcp端口

- modules/havenask-engine/src/main/java/org/havenask/engine/NativeProcessControlService.java
- modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HavenaskEngine.java
避免关闭节点时，searcher进程已经关闭，还会更新seacher target问题
> 避免关闭节点时，searcher进程已经关闭，还会更新seacher target问题

- modules/havenask-engine/src/main/java/org/havenask/engine/NativeProcessControlService.java
通过修改启动命令，记录脚本运行日志，searcher、qrs启动脚本目前可以正常退出
> 修复fed启动时，启动searcher、qrs的脚本不退出问题

- modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskIndexSettingProvider.java
- modules/havenask-engine/src/test/java/org/havenask/engine/HavenaskIndexSettingProviderTests.java
普通索引不默认加上replica=0配置，只有havenask索引才添加
> 只有在创建havenask索引时，才自动加上replica=0

- modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskEnginePlugin.java
- modules/havenask-engine/src/test/java/org/havenask/engine/HavenaskEnginePluginTests.java
开启havenask engine的方式，在yml配置文件中需同时添加：
discovery.type: single-node
havenask.engine.enabled: true
> 增加校验：只有在discovery.type设置为single-node时，才能开启havenask engine

- distribution/docker/build.gradle
- distribution/docker/src/docker/Dockerfile
- script/create_container.sh
添加opensearch-dashboard到镜像中，启动镜像后，可以通过如下方式启动opensearch-dashboard(先确保havenask federation进程已正常启动)：
```
cd dashboards
./bin/opensearch-dashboards
```
启动dashboard后，在浏览器访问节点的5601端口，比如在本地启动的话，在浏览器访问：http://127.0.0.1:5601/
> 添加opensearch-dashboard到镜像中，可以支持可视化查看havenask索引

- modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskEngineEnvironment.java
- modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskEnginePlugin.java
- modules/havenask-engine/src/main/java/org/havenask/engine/NativeProcessControlService.java
- modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HavenaskEngine.java
- modules/havenask-engine/src/test/java/org/havenask/engine/HavenaskEngineEnvironmentTests.java
- server/src/main/java/org/havenask/env/NodeEnvironment.java
- server/src/main/java/org/havenask/node/Node.java
- server/src/main/java/org/havenask/plugins/NodeEnvironmentPlugin.java
增加NodeEnvironmentPlugin，在NodeEnvironment执行deleteIndexDirectoryUnderLock和deleteShardDirectoryUnderLock时调用plugin的deleteIndexDirectoryUnderLock和deleteShardDirectoryUnderLock方法
> 增加env plugin，支持在NodeEnvironment删除索引文件时，删除plugin的文件

- server/src/main/java/org/havenask/rest/action/admin/indices/RestCreateIndexAction.java
由于havenask创建数据表的耗时比较长，很容易触发创建索引timeout。
默认改为不等待shard active可以避免该问题。
修改rest层的配置，测试用例能全部通过
> 创建索引，默认配置改为不等待shard active

- modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/SchemaGenerate.java
- modules/havenask-engine/src/test/java/org/havenask/engine/index/engine/SchemaGenerateTests.java
优化mapping到havenask schema的转换：
- 对于不支持的类型，比如nested或者其他不支持字段，直接抛出异常
- 不传递mapping时，创建默认shcema文件
> 优化mapping到havenask schema的转换

- server/src/main/java/org/havenask/rest/action/admin/indices/RestCreateIndexAction.java
修复 [#37](https://github.com/alibaba/havenask-federation/pull/37) bug，多设置了createIndexRequest.waitForActiveShards，并只有havenask索引才默认设置为None
> 修复创建索引waitForActiveShards设置未生效

- modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskIndexSettingProvider.java
- modules/havenask-engine/src/test/java/org/havenask/engine/HavenaskIndexSettingProviderTests.java
This reverts commit ab7cb9c7c67675b96c702ca189bb82d8dd42b1ef.
index.mapper.dynamic参数已经废弃，用来控制新增type，而不是field，所以功能上有歧义，而且目前只支持单type，所以revert该修改
> Revert "增加默认参数index.mapper.dynamic，设置为false，不支持动态mapping (#40)"

- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskEngineEnvironment.java
- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskEnginePlugin.java
- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/HavenaskIndexEventListener.java
- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/config/generator/BizConfigGenerator.java
- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/config/generator/TableConfigGenerator.java
- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HavenaskEngine.java
- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/SchemaGenerate.java
- elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/HavenaskEngineEnvironmentTests.java
- elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/config/generator/BizConfigGeneratorTests.java
- elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/config/generator/TableConfigGeneratorTests.java
- elastic-fed/server/src/main/java/org/havenask/index/CompositeIndexEventListener.java
- elastic-fed/server/src/main/java/org/havenask/index/codec/CodecService.java
- elastic-fed/server/src/main/java/org/havenask/index/engine/EngineConfig.java
- elastic-fed/server/src/main/java/org/havenask/index/engine/InternalEngine.java
- elastic-fed/server/src/main/java/org/havenask/index/shard/IndexEventListener.java
- elastic-fed/server/src/main/java/org/havenask/indices/cluster/IndicesClusterStateService.java
创建havenask的配置从shard级别在engine层创建，改成了在index级别创建。
删除havenask的配置从shard级别在engine层close时删除，改成了在索引删除时删除配置。
这样修改完成后，仍然无法支持open、close接口，后续需要针对性开发支持open、close接口。
> 创建、删除索引和havenask的交互重构

- elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/NativeProcessControlServiceTests.java
相关issue：https://github.com/alibaba/havenask-federation/issues/78
> NativeProcessControlServiceTests经常出现启动多个进程导致的检查失败，暂时屏蔽

- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/NativeProcessControlService.java
target一旦更新成功，之后的更新命令会很快执行完成，并发执行反倒可能导致异常行为
> 更新target加上synchronized锁，防止并发更新

- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HavenaskEngine.java
在更新searcher target后，检查table是否正常加载。
持续检查table是否正常加载，直到加载成功，或者检查5分钟后超时。
> 在创建索引，启动engine时，检查searcher数据表是否正常加载

- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/NativeProcessControlService.java
当searcher和qrs启动失败再次循环启动时，增加了1s的sleep
> 当searcher和qrs启动失败再次循环启动时，增加了sleep机制

- elastic-fed/modules/havenask-engine/config/havenask/command/general_search_starter.py
之前searcher、qrs一启动，就会有400%的cpu一直在run，加上FSLIB_LOCAL_ASYNC_CORO_READ=0参数后，修复该问题
> 增加参数FSLIB_LOCAL_ASYNC_CORO_READ=0，防止cpu启动就飙高

- elastic-fed/modules/havenask-engine/config/havenask/command/general_search_updater.py
修复新建索引无法查询的问题。
增加直写配置后，searcher不会更新cm2的version，导致qrs无法更新target。现在加上随机值，确保qrs正常更新。
> searcher更新数据表时，更新zone的version值，以提供qrs更新

- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HavenaskEngine.java
开启realTimeEnable使用的是kafka模式，默认是关闭，支持只写
> 修复delete文档的错误逻辑

- elastic-fed/qa/havenask-docker/build.gradle
- elastic-fed/qa/havenask-docker/docker-compose.yml
- elastic-fed/qa/havenask-docker/docker-test-entrypoint.sh
- elastic-fed/qa/havenask-docker/src/test/java/org/havenask/cluster/remote/test/AbstractHavenaskClusterTestCase.java
- elastic-fed/qa/havenask-docker/src/test/java/org/havenask/cluster/remote/test/BasicIT.java
在qa/havenask-docker模块增加fed的集成测试框架，支持拉起一个docker，启动fed进程。进行真实环境的的集成测试。
> 添加启动havenask docker的集成测试用例框架

- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/CheckpointCalc.java
- elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/engine/CheckpointCalcTests.java
在原有错误说明的基础上增加了“illegal value: XXX”
> 输入非法构造参数时，显示非法参数的具体值

- elastic-fed/buildSrc/src/main/java/org/havenask/gradle/test/RestTestBasePlugin.java
- elastic-fed/modules/havenask-engine/build.gradle
- elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/AbstractHavenaskRestTestCase.java
- elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/BasicIT.java
使用方式：
```
/gradlew javaRestTest -p modules/havenask-engine -Dtests.rest.cluster="xxx:9200"
```
> 支持配置远端地址进行集成测试

- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/NativeProcessControlService.java
- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HavenaskEngine.java
fed重启能直接进入recovery环节。但是searcher重启，fed如果在engine层感知不到的话，会导致无法恢复数据，从而可能导致数据丢失。
在检测到searcher离线，进行重启的流程前，先failed节点上全部的havenask engine shard，这样在searcher后，能进入recovery shard流程
> 支持在searcher重启前，先failed 节点的havenask engine shard，进入recovery环节

- elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/AbstractHavenaskRestTestCase.java
preserveClusterUponCompletion默认返回false，会在测试后删除所有索引，现在先改成返回true保留索引，方便调试。
> 重载方法，方便自适应选择集成测试后是否保留索引

- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/rpc/arpc/SearcherArpcClient.java
之前arpc如果长时间不写索引时连接会关闭，现在连接失败后会进行一次channel reset并重试
> 写入失败后会进行重试，防止长时间不写入导致arpc连接关闭

- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HavenaskEngine.java
- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/rpc/arpc/SearcherArpcClient.java
- elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/engine/HavenaskEngineTests.java
解决：https://github.com/alibaba/havenask-federation/issues/125 和 https://github.com/alibaba/havenask-federation/issues/156
同时在压测时，也经常出现队列打满，所以增加了退避重试功能
> 增加写入的退避重试，解决连接断开和havenask写入队列打满的问题

- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HavenaskEngine.java
由于havenask的写入协议是文本协议，直接将二进制数据装入String会出现格式混乱甚至格式错误，现在统一将内容写入_source前转为JSON格式。
> 统一按JSON格式将_source写入havenask

- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HavenaskEngine.java
- elastic-fed/server/src/main/java/org/havenask/index/engine/InternalEngine.java
在dev镜像中以debug模式启动时会产生assert error，原因是isWarmedUp未置true，而此变量对于havenask引擎无影响，故暂时屏蔽。
> 修复了isWarmedUp引起debug时的崩溃bug

- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskEnginePlugin.java
- elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/config/generator/BizConfigGeneratorTests.java
- elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/config/generator/SchemaGeneratorTests.java
- elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/config/generator/TableConfigGeneratorTests.java
- elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/mapper/DenseVectorFieldMapperTests.java
havenask开启直写参数后，schema有向量索引会加载失败，具体见：https://github.com/alibaba/havenask/issues/118。
所以先暂时屏蔽，等havenask解决后再开启
> 暂时屏蔽向量索引的字段类型，等使用havenask最新版本再放开

- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskEnginePlugin.java
- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/NativeProcessControlService.java
- elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/MockNativeProcessControlService.java
- elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/NativeProcessControlServiceTests.java
searcher重启后会执行_cluster/reroute?retry_failed=true, 不然可能会导致searcher重启但节点还是RED
> searcher重启后会执行_cluster/reroute?retry_failed=true

- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HavenaskIndexSearcher.java
- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/search/HavenaskFetchPhase.java
fetch拿到的是doc id列表，是int类型，通过在ReaderContext中cache id映射，根据doc id获取到主键id，再进行fetch查询
> query阶段，在ReaderContext中cache id映射

- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/QueryTransformer.java
- elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/engine/QueryTransformerTests.java
支持search的match all query，这样在search接口不传DSL时，能查出数据
> 支持search的match all query

- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HavenaskEngine.java
> 更新target同步方法，解决qrs更新异常问题

- elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/search/fetch/HavenaskFetchPhaseTests.java
增加source过滤的单元测试,测试了include与exclude、FetchSourceContext只为true和false以及模糊匹配的测试。
结果符合预期。
> 增加source过滤的单元测试

- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/MetaDataSyncer.java
fix：https://github.com/alibaba/havenask-federation/issues/263
元数据发生变更时，先清掉searcherTargetInfo，防止获取到之前的searcherTargetInfo，误判为searcher已经更新成功。
> 修复反复创建相同索引的异常case

- elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/AbstractHavenaskRestTestCase.java
- elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/BasicIT.java
- elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/DocIT.java
- elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/FlushIT.java
- elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/MappingIT.java
- elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/RecoveryIT.java
- elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/SearchIT.java
将一些内容封装成方法
增加cleanIndices()方法, 用于清理测试失败后的索引
修复了一些更新后DocIT存在的问题
fix#307
> javaRestTest测试用例优化，修复了一些更新后相关测试存在的问题

- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HavenaskEngine.java
- elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/engine/HavenaskEngineTests.java
失败的示例如下：
```
2> REPRODUCE WITH: ./gradlew ':modules:havenask-engine:javaRestTest' --tests "org.havenask.engine.BasicIT.testCreateAndDeleteSameIndex" -Dtests.seed=1E20C03E619D2D5A -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1" -Dtests.locale=sq -Dtests.timezone=Israel -Druntime.java=11
2> HavenaskStatusException[Havenask exception [type=i_o_exception, reason=havenask index exception, error code: TBS_ERROR_OTHERS, error message:no valid table/range for WriteRequest table: create_and_delete_same_index_test hashid: 25383]]
at __randomizedtesting.SeedInfo.seed([1E20C03E619D2D5A:DFEB312DE1DAC51B]:0)
at org.havenask.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:207)
at org.havenask.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1680) …
```
> 写入数据时偶尔出现table未ready，写入重试增加该错误类型的判断

- elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/FlushIT.java
- elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/PeerRecoveryIT.java
- elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/RecoveryIT.java
增加node数量判断，根据node数量跳过不符合的测试:
节点数量小于2时跳过PeerRecoveryIT
节点数量大于1时跳过RecoveryIT的testRecoverySingleShard()
> 增加peer recovery流程的javaRestTest

- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/HavenaskIndexEventListener.java
afterIndexCreated调用时，mapping还没ready，导致config生成的schema异常，改成afterIndexMappingUpdate后，可以正常生成schema
> 修复havenask config配置schema异常问题

- elastic-fed/distribution/src/bin/havenask-command/general_search_starter.py
fix: https://github.com/alibaba/havenask-federation/issues/364
> 支持searcher启动时不加载target，由fed加载

- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/search/HavenaskSearchFetchProcessor.java
- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/search/HavenaskSearchQueryProcessor.java
- elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/search/fetch/HavenaskSearchFetchProcessorTests.java
- elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/search/fetch/HavenaskSearchQueryProcessorTests.java
fix:https://github.com/alibaba/havenask-federation/issues/370
> 修复索引名中含有中划线时，sql会报错的问题

- elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/util/UtilsTests.java
fix https://github.com/alibaba/havenask-federation/issues/395
增加@LuceneTestCase.SuppressFileSystems("ExtrasFS")注入，防止测试case可能生成临时文件影响测试结果。
> 修复testCleanVersionPublishFiles偶尔失败的case

- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HavenaskEngine.java
- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/mapper/DenseVectorFieldMapper.java
- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/search/HavenaskSearchQueryProcessor.java
- elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/engine/HavenaskEngineTests.java
- elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/mapper/DenseVectorFieldMapperTests.java
- elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/search/fetch/HavenaskSearchQueryProcessorTests.java
fix:https://github.com/alibaba/havenask-federation/issues/402
目前查询需要使用'_'而不是es的'.'来分隔Object对象的子fieldname
> 修复search接口查询不到Object对象的子fieldname的问题

- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HavenaskEngine.java
1、在doc count为0时，不缓存
2、增加了checkpoint的比较
> 优化doc stats的缓存机制

- elastic-fed/modules/havenask-engine/src/internalClusterTest/java/org/havenask/engine/stop/HavenaskStopActionIT.java
- elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/PeerRecoveryIT.java
- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/stop/action/HavenaskStopNodeRequest.java
- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/stop/action/HavenaskStopNodeResponse.java
- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/stop/action/HavenaskStopRequest.java
- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/stop/action/HavenaskStopResponse.java
- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/stop/action/TransportHavenaskStopAction.java
- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/stop/rest/RestHavenaskStop.java
现在可以通过设置node参数指定由哪个node进行kill searcher的操作，未指定时，所有节点都执行kill searcher的操作。
e.g.
#所有节点都执行kill searcher操作
POST /_havenask/stop?role=searcher
#node1 执行kill searcher操作
POST /_havenask/stop?role=searcher&node=node1
#node1、node2 与node3 执行kill searcher操作
POST /_havenask/stop?role=searcher&node=node1,node2,node3
> fed分布式适配kill havenask searcher的rest接口

- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskEnginePlugin.java
- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/create/rest/RestHavenaskCreate.java
- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/config/generator/BizConfigGenerator.java
- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/config/generator/TableConfigGenerator.java
- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/EngineSettings.java
- elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/config/generator/BizConfigGeneratorTests.java
- elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/config/generator/TableConfigGeneratorTests.java
新增了一个`PUT _havenask/create/${index}`的REST接口，支持用户自定义havenask引擎配置
```
#e.g.
PUT _havenask/create/test
{
"settings": {
"number_of_shards":2,
"number_of_replicas": 0
},
"mappings": {
"properties": {
"foo": {
"type": "keyword"
}
}
},
"cluster":{
//cluster.json配置
},
"data_table":{
//data_table.json配置
},
"schema":{
//schema.json配置
}
}
```
目前如果用户设置了对应的配置，则会直接将用户对相关参数的配置直接写到对应的.json文件下，
没有配置则会根据之前的流程生成对应的配置。
后续会支持参数的校验等功能。
> 增加创建havenask索引时支持配置havenask参数的REST接口

- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/MetaDataSyncer.java
- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/store/HavenaskStore.java
- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/rpc/TargetInfo.java
- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/util/Utils.java
- elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/MetaDataSyncerTests.java
- elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/util/UtilsTests.java
fix:https://github.com/alibaba/havenask-federation/issues/440
> 修复MetaDataSyncer获取Partition的incVersion时可能存在的npe问题

- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HavenaskEngine.java
fix: https://github.com/alibaba/havenask-federation/issues/470
现在fed在没有写入文档时，checkpoint没有变化时，lucene segment metadata的version随着havenask的version更新而更新
> 优化lucene segment metadata的更新逻辑

- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/EngineSettings.java
> 支持一些havenask索引参数动态更新

- elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/rpc/http/QrsHttpClient.java
之前使用默认的Consts.ISO_8859_1编码，编码中文存在问题，导致全文检索无法检索到中文以及sql结果乱码，修改为UTF-8编码;
> qrs sql接口post body使用UTF-8编码
