alibaba/havenask-federation

modules/havenask-engine/build.gradle
modules/havenask-engine/src/internalClusterTest/java/org/havenask/OkHttpThreadLeakFilter.java
modules/havenask-engine/src/internalClusterTest/java/org/havenask/engine/HavenaskITTestCase.java
modules/havenask-engine/src/internalClusterTest/java/org/havenask/engine/rpc/http/QrsHttpClientIT.java
modules/havenask-engine/src/internalClusterTest/java/org/havenask/engine/search/action/SqlActionIT.java
modules/havenask-engine/src/internalClusterTest/java/org/havenask/engine/search/action/SqlActionNoIngestIT.java
modules/havenask-engine/src/internalClusterTest/plugin-metadata/plugin-security.policy
modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskEnginePlugin.java
modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HavenaskEngine.java
modules/havenask-engine/src/main/java/org/havenask/engine/rpc/HavenaskClient.java
modules/havenask-engine/src/main/java/org/havenask/engine/rpc/QrsClient.java
modules/havenask-engine/src/main/java/org/havenask/engine/rpc/QrsSqlRequest.java
modules/havenask-engine/src/main/java/org/havenask/engine/rpc/QrsSqlResponse.java
modules/havenask-engine/src/main/java/org/havenask/engine/rpc/http/HavenaskHttpClient.java
modules/havenask-engine/src/main/java/org/havenask/engine/rpc/http/QrsHttpClient.java
modules/havenask-engine/src/main/java/org/havenask/engine/search/action/HavenaskSqlAction.java
modules/havenask-engine/src/main/java/org/havenask/engine/search/action/HavenaskSqlRequest.java
modules/havenask-engine/src/main/java/org/havenask/engine/search/action/HavenaskSqlResponse.java
modules/havenask-engine/src/main/java/org/havenask/engine/search/action/TransportHavenaskSqlAction.java
modules/havenask-engine/src/main/java/org/havenask/engine/search/rest/RestHavenaskSqlAction.java
modules/havenask-engine/src/main/java/org/havenask/engine/util/VersionUtils.java
modules/havenask-engine/src/test/java/org/havenask/engine/search/action/HavenaskSqlRequestTests.java
modules/havenask-engine/src/test/java/org/havenask/engine/search/rest/RestHavenaskSqlActionTests.java

支持havenask sql接口。
可以通过`GET /_havenask/sql`接口，通过sql查询havenask数据

支持havenask sql接口

---

modules/havenask-engine/src/main/java/org/havenask/engine/index/config/BizConfig.java
modules/havenask-engine/src/main/java/org/havenask/engine/index/config/ZoneBiz.java
modules/havenask-engine/src/main/java/org/havenask/engine/index/config/generator/BizConfigGenerator.java
modules/havenask-engine/src/test/java/org/havenask/engine/index/config/generator/BizConfigGeneratorTests.java

支持创建、删除索引时更新zone配置

---

modules/havenask-engine/src/internalClusterTest/java/org/havenask/engine/search/action/SqlActionIT.java
modules/havenask-engine/src/internalClusterTest/java/org/havenask/engine/search/action/SqlActionNoIngestIT.java

修复sql相关的测试用例偶尔失败的bug

---

modules/havenask-engine/src/main/java/org/havenask/engine/index/config/ZoneBiz.java
modules/havenask-engine/src/main/java/org/havenask/engine/index/config/generator/BizConfigGenerator.java
modules/havenask-engine/src/main/java/org/havenask/engine/index/config/generator/TableConfigGenerator.java
modules/havenask-engine/src/test/java/org/havenask/engine/index/config/generator/BizConfigGeneratorTests.java

修复biz zone config配置异常:
1. 修复配置中少了turing_options_config一层
2. 修复写入覆盖异常，写入增加了TRUNCATE_EXISTING模式

修复biz zone config配置异常

---

modules/havenask-engine/config/havenask/script/general_search_updater.py
modules/havenask-engine/src/main/java/org/havenask/engine/NativeProcessControlService.java
modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HavenaskEngine.java

在创建、删除索引时，调用update qrs target的脚本，来更新qrs配置信息

创建、删除索引时调用qrs更新target

---

modules/havenask-engine/src/main/java/org/havenask/engine/NativeProcessControlService.java

执行脚本代码相关优化

---

modules/havenask-engine/config/havenask/script/bs_job_starter.py
modules/havenask-engine/config/havenask/script/general_search_starter.py
modules/havenask-engine/config/havenask/script/general_search_updater.py

在实际运行中，更新配置偶尔会出现timeout问题。所以将timeout参数调整会跟之前一样。
之后会另外解决update target时间太长，导致cluster task卡顿，timeout等问题

script timeout时间调整回跟之前一样，防止出现timeout问题

---

modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskEnginePlugin.java

加上下面四个参数：
- NativeProcessControlService.HAVENASK_SEARCHER_HTTP_PORT_SETTING
- NativeProcessControlService.HAVENASK_SEARCHER_TCP_PORT_SETTING
- NativeProcessControlService.HAVENASK_QRS_HTTP_PORT_SETTING
- NativeProcessControlService.HAVENASK_QRS_TCP_PORT_SETTING

plugin getSettings方法加上遗漏的setting参数

---

modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskEnginePlugin.java
server/src/main/java/org/havenask/cluster/metadata/MetadataCreateIndexService.java
server/src/main/java/org/havenask/index/shard/IndexMappingProvider.java
server/src/main/java/org/havenask/node/Node.java
server/src/main/java/org/havenask/plugins/Plugin.java
server/src/test/java/org/havenask/cluster/metadata/MetadataCreateIndexServiceTests.java

支持在插件中增加自定义mapping功能，同时在havenask enginemodule中增加dynamic为false的设置

支持在插件中增加自定义mapping功能

---

modules/havenask-engine/src/main/java/org/havenask/engine/NativeProcessControlService.java

确保started的时候，searcher、qrs进程已启动完成

先进行一次进程状态的检查和启动, 再添加到定时任务

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HashAlgorithm.java

havenask issue有用户提到HashAlgorithm bug：https://github.com/alibaba/havenask/issues/67
将havenask的修复PR同步到fed：https://github.com/alibaba/havenask/pull/69

修复HashAlgorithm bug

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskEnginePlugin.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskIndexMappingProvider.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/HavenaskIndexEventListener.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/config/generator/BizConfigGenerator.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/config/generator/TableConfigGenerator.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/SchemaGenerate.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/config/generator/BizConfigGeneratorTests.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/config/generator/TableConfigGeneratorTests.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/engine/SchemaGenerateTests.java
elastic-fed/server/src/main/java/org/havenask/cluster/metadata/MetadataCreateIndexService.java
elastic-fed/server/src/main/java/org/havenask/index/shard/IndexMappingProvider.java
elastic-fed/server/src/test/java/org/havenask/cluster/metadata/MetadataCreateIndexServiceTests.java

IndexMappingProvider增加一个validateIndexMapping方法，校验mapping是否合理。
并在Havenask modules里校验schema

IndexMappingProvider增加一个validateIndexMapping方法，校验mapping是否合理

---

elastic-fed/buildSrc/src/main/java/org/havenask/gradle/DockerBase.java

镜像从havenask/ha3_runtime替换成registry.cn-hangzhou.aliyuncs.com/havenask/ha3_runtime

ha3_runtime使用国内镜像，提高pull速度

---

elastic-fed/libs/arpc/build.gradle
elastic-fed/modules/havenask-engine/build.gradle

change protoc to 3.17.3 to support m2

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/util/Utils.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/util/UtilsTests.java

fix:https://github.com/alibaba/havenask-federation/issues/107

修正了getCheckpoint中测试路径的问题

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/search/rest/RestHavenaskSqlAction.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/search/rest/RestHavenaskSqlActionTests.java

havenask 1.0版本开始，sql接口必须传递databaseName，databaseName在fed是默认配置的，名称为general，所以此处在fed的sql接口默认加上

sql默认添加databaseName，名称为general

---

elastic-fed/script/create_container.sh

modify script, add --net=host to docker run

modify script

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HavenaskEngine.java
elastic-fed/server/src/main/java/org/havenask/index/engine/InternalEngine.java

支持flush havenask的checkpoint的功能，还要结合refresh设置havenask checkpoint才能完整生效。

支持flush havenask的checkpoint

---

elastic-fed/script/create_container.sh

对Linux和Mac、Windows自适应选择端口映射

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/util/Utils.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/util/UtilsTests.java

更新了checkpoint的获取接口，现在是从locator字段获取checkpoint

---

elastic-fed/buildSrc/version.properties

更新havenask镜像版本到1.0.0-beta3

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskEnginePlugin.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/config/generator/BizConfigGenerator.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/config/generator/TableConfigGenerator.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/EngineSettings.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/config/generator/BizConfigGeneratorTests.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/config/generator/TableConfigGeneratorTests.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/engine/EngineSettingsTests.java

支持创建索引时动态配置max_doc_count，finish #135 。

增加了index.havenask.max_doc_count字段的支持

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/CheckpointCalc.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/engine/CheckpointCalcTests.java

增加了参数注释，milis修正为millis，默认值的millisPerSegment调小，segmentSize调大。

CheckpointCalc的参数增加了注释，并修正了拼写错误，更改了默认值

---

elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/BasicIT.java

增加了更多的基础测试用例

---

elastic-fed/buildSrc/src/main/java/org/havenask/gradle/testclusters/HavenaskNode.java
elastic-fed/buildSrc/src/main/java/org/havenask/gradle/testclusters/RunTask.java
elastic-fed/gradle/run.gradle

支持可以通过gradle run命令启动fed

---

elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/BasicIT.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskEnginePlugin.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HavenaskEngine.java
elastic-fed/server/src/main/java/org/havenask/index/engine/TranslogLeafReader.java

在engine的get方法中通过调用qrs sql接口获取id数据，支持了fed的get和update接口

支持get、update接口

---

elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/engine/HavenaskEngineTests.java
elastic-fed/test/framework/src/main/java/org/havenask/index/engine/EngineTestCase.java

之前提交 #165 时未附测试用例，这次提交增加相关单元测试。

增加了对于_source应用不同XContentType的单元测试

---

elastic-fed/buildSrc/src/main/java/org/havenask/gradle/test/RestTestBasePlugin.java
elastic-fed/buildSrc/src/main/java/org/havenask/gradle/testclusters/HavenaskNode.java
elastic-fed/distribution/build.gradle
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskEnginePlugin.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskIndexSettingProvider.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/HavenaskIndexSettingProviderTests.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/config/generator/BizConfigGeneratorTests.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/config/generator/SchemaGeneratorTests.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/config/generator/TableConfigGeneratorTests.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/mapper/DenseVectorFieldMapperTests.java
elastic-fed/rest-api-spec/build.gradle
elastic-fed/rest-api-spec/src/main/resources/rest-api-spec/test/indices.create/10_basic.yml
elastic-fed/rest-api-spec/src/main/resources/rest-api-spec/test/indices.create/11_basic_with_types.yml
elastic-fed/test/framework/src/main/java/org/havenask/test/junit/listeners/ReproduceInfoPrinter.java
elastic-fed/test/framework/src/main/java/org/havenask/test/rest/yaml/HavenaskClientYamlSuiteTestCase.java

运行示例命令：
```
./gradlew yamlRestTest -p rest-api-spec -Dtests.engine=havenask
```
要以havenask引擎运行的方式，需要在build.gradle中添加如下示例：
```
yamlRestTest {
if (System.getProperty("tests.engine") == "havenask") {
systemProperty 'tests.rest.whitelist', [
'indices.create/*/*'
].join(",")
}
}
testClusters.yamlRestTest {
if (System.getProperty("tests.engine") == "havenask") {
setting 'network.host', '0.0.0.0'
setting 'discovery.type', 'single-node'
setting 'havenask.engine.enabled', 'true'
setting 'havenask.engine.set_default_engine', 'true'
}
}
```

支持白名单的方式运行yaml测试用例

---

elastic-fed/modules/havenask-engine/src/internalClusterTest/java/org/havenask/engine/CheckTargetServiceIT.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/CheckTargetService.java

运行CheckTargetService任务切换为havenask自己的线程。
close https://github.com/alibaba/havenask-federation/issues/178

修复CheckTargetService scheduler线程Blocking operation异常

---

elastic-fed/script/dev/Dockerfile

修复dev dockerfile无法run的问题

---

elastic-fed/modules/havenask-engine/src/internalClusterTest/java/org/havenask/engine/CheckTargetServiceIT.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/CheckTargetService.java

Close https://github.com/alibaba/havenask-federation/issues/186

修复CheckTargetServiceIT随机出现的错误情况

---

elastic-fed/modules/havenask-engine/src/internalClusterTest/java/org/havenask/engine/CheckTargetServiceIT.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/CheckTargetService.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/NativeProcessControlServiceTests.java

1、重启开启误注释的AwaitsFix，并缩小AwaitsFix的范围到具体method
2、优化CheckTargetServiceIT.testCheckDataNode

test case相关优化

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HavenaskEngine.java

优化了HavenaskEngine的日志以及增加了refresh及flush重要方法的注释，方便开发者查看代码逻辑

优化了HavenaskEngine的日志以及增加了refresh及flush重要方法的注释

---

elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/NativeProcessControlServiceTests.java

修复Check时的RandomSeed错误

---

elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/FlushIT.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/CheckpointCalc.java

增加了flush相关的集成测试

---

elastic-fed/client/rest-high-level/src/main/java/org/havenask/client/ha/SqlResponse.java
elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/RecoveryIT.java

增加了Recovery相关的集成测试

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/CheckTargetService.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskEngineEnvironment.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/HavenaskIndexEventListener.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/EngineSettings.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HavenaskEngine.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HavenaskIndexSearcher.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/util/Utils.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/HavenaskEngineEnvironmentTests.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/engine/EngineSettingsTests.java

解除number_of_shards只能为1的限制。
havenask表名为indexName_shardId，这样通过sql也得指定shard查询，之后会更好的支持sql。

fed支持havenask使用多shards索引

---

elastic-fed/modules/havenask-engine/src/internalClusterTest/java/org/havenask/engine/HavenaskITTestCase.java
elastic-fed/modules/havenask-engine/src/internalClusterTest/java/org/havenask/engine/search/SearchIT.java
elastic-fed/modules/havenask-engine/src/internalClusterTest/java/org/havenask/engine/search/action/SqlActionIT.java

Closed https://github.com/alibaba/havenask-federation/issues/217

修复SearchIT的failed test

---

elastic-fed/modules/havenask-engine/src/internalClusterTest/java/org/havenask/engine/CheckTargetServiceIT.java

Closed: https://github.com/alibaba/havenask-federation/issues/236

修复testCheckIngestNode case偶尔失败的情况

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HavenaskIndexSearcher.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/QueryTransformer.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/query/ProximaQueryBuilder.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/engine/QueryTransformerTests.java

支持将dsl的size、from转换成sql limit

---

elastic-fed/modules/havenask-engine/src/internalClusterTest/java/org/havenask/engine/search/SearchIT.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/search/HavenaskFetchPhase.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/search/fetch/FetchSourcePhase.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/search/fetch/FetchSubPhase.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/search/fetch/FetchSubPhaseProcessor.java

增加了source过滤的模块
目前支持 include 与exclude功能

增加source过滤模块

---

elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/SearchIT.java

增加knn query的javaRestTest
测试了单shard以及多shard场景下的knn查询的整个流程
结果符合预期

增加knn query的javaRestTest

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskEnginePlugin.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/store/HavenaskStore.java
elastic-fed/server/src/main/java/org/havenask/index/IndexService.java
elastic-fed/server/src/main/java/org/havenask/plugins/IndexStorePlugin.java

支持peer-recovery需求，在store中获取的phase1文件列表就包含了havenask segment文件

增加store plugin，支持自定义store

---

elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/BasicIT.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/MetaDataSyncer.java

fix: https://github.com/alibaba/havenask-federation/issues/209

修复org.havenask.engine.BasicIT.testIndexMethod case偶尔会报错的问题

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HavenaskIndexSearcher.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/QueryTransformer.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/search/HavenaskFetchPhase.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/engine/HavenaskIndexSearcherTests.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/engine/QueryTransformerTests.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/search/fetch/HavenaskFetchPhaseTests.java

support:https://github.com/alibaba/havenask-federation/issues/272

向量查询支持默认按向量相似度排序

---

elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/DocIT.java
elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/SearchIT.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/QueryTransformer.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/mapper/DenseVectorFieldMapper.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/engine/QueryTransformerTests.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/mapper/DenseVectorFieldMapperTests.java

增加对向量similarity类型为dot_product时的参数校验，此时需要向量为单位向量（即模长为1）
增加相关测试样例，测试结果符合预期

增加内积类型向量的参数检查

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/QueryTransformer.java

fix:https://github.com/alibaba/havenask-federation/issues/298

修复向量索引查询不存在字段时报NPE的问题

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/MetaDataSyncer.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/config/generator/BizConfigGenerator.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/config/generator/BizConfigGeneratorTests.java

fixed https://github.com/alibaba/havenask-federation/issues/280

zone内的table更新，调整到MetaDataSyncer模块

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/search/HavenaskFetchPhase.java

fix:https://github.com/alibaba/havenask-federation/issues/325

修复传递_source为false时仍然返回source的问题

---

elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/AbstractHavenaskRestTestCase.java
elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/BasicIT.java
elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/DocIT.java
elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/PeerRecoveryIT.java
elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/RecoveryIT.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskEngineEnvironment.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskEnginePlugin.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/MetaDataSyncer.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/HavenaskIndexEventListener.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/HavenaskEngineEnvironmentTests.java

fix: https://github.com/alibaba/havenask-federation/issues/324

异步清理删除索引后runtimedata相关的数据信息，加锁解决反复创建删除索引导致的并发问题

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/MetaDataSyncer.java

fix:https://github.com/alibaba/havenask-federation/issues/346

优化shard级别变更时更新qrs的判断逻辑

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/search/HavenaskSearchFetchProcessor.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/search/HavenaskSearchQueryProcessor.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/search/fetch/HavenaskSearchFetchProcessorTests.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/search/fetch/HavenaskSearchQueryProcessorTests.java

fix : https://github.com/alibaba/havenask-federation/issues/354

search接口不传递size、from时，默认值设置为10

---

elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/config/generator/SchemaGeneratorTests.java

fix:https://github.com/alibaba/havenask-federation/issues/389

更新向量索引适配v2参数的unit test

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskEngineEnvironment.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HavenaskEngine.java

fix:https://github.com/alibaba/havenask-federation/issues/388

优化删除索引时，checkShardIsDeletedInSearcher的逻辑

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/MetaDataSyncer.java

fix:https://github.com/alibaba/havenask-federation/issues/398

优化MetaDataSyncer.getIndexNames方法

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/cluster/routing/allocation/decider/HavenaskShardsLimitAllocationDecider.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskEnginePlugin.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/cluster/routing/allocation/decider/HavenaskShardsLimitAllocationDeciderTests.java

fix:https://github.com/alibaba/havenask-federation/issues/369

增加单节点havenask索引shard数量的限制

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HavenaskIndexSearcher.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/QueryTransformer.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/engine/QueryTransformerTests.java

fix:https://github.com/alibaba/havenask-federation/issues/412

适配之前分布式架构在多节点情况下的search接口

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/store/HavenaskDirectory.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/store/HavenaskStore.java

fix https://github.com/alibaba/havenask-federation/issues/423

由于文件可能被havenask修改，增加重试来防止文件异常

---

elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/DocIT.java
elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/FlushIT.java
elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/PeerRecoveryIT.java
elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/RoutingIT.java

javaRestTest适配 https://github.com/alibaba/havenask-federation/pull/419 修改的havenask表的参数

javaRestTest适配havenask表参数优化

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/store/HavenaskStore.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/store/HavenaskStoreTests.java

fix:https://github.com/alibaba/havenask-federation/issues/320

修复解析entry_table可能存在的bad case

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/search/HavenaskSearchFetchProcessor.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/search/action/TransportHavenaskSearchAction.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/search/fetch/HavenaskSearchFetchProcessorTests.java

fix:https://github.com/alibaba/havenask-federation/issues/438

创建索引时，如果_source设置了enabled为false，则fetch阶段不查询_source

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/search/HavenaskSearchQueryProcessor.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/search/fetch/HavenaskSearchQueryProcessorTests.java

term查询的fieldName字段增加反引号，防止查询部分fieldName结果为空的情况

优化term查询的sql语句

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/MetaDataSyncer.java

fix: https://github.com/alibaba/havenask-federation/issues/439

修复启动时，MetaDataSyncer偶尔出现的NPE问题

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/config/generator/SchemaGenerator.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/mapper/DenseVectorFieldMapper.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/config/generator/SchemaGeneratorTests.java

向量索引参数增加proxima.oswg.streamer.segment_size参数;
不配置默认情况下该参数值为2Mb。

向量索引参数增加proxima.oswg.streamer.segment_size参数

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskIndexSettingProvider.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/engine/HavenaskEngine.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/search/HavenaskSearchFetchProcessor.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/HavenaskIndexSettingProviderTests.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/index/engine/HavenaskEngineTests.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/search/fetch/HavenaskSearchFetchProcessorTests.java

fix : https://github.com/alibaba/havenask-federation/issues/509

修复写入带routing值导致的havenask索引路由异常问题

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/search/rest/RestHavenaskSqlAction.java

fix : https://github.com/alibaba/havenask-federation/issues/514

修复fed debug模式下执行sql语句报错问题

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskEngineEnvironment.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/HavenaskEngineEnvironmentTests.java

fix : https://github.com/alibaba/havenask-federation/issues/503

删除索引后异步移除索引runtime目录时增加重试, 避免删除失败

---

elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/HavenaskIndexMappingProvider.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/create/rest/RestHavenaskCreate.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/HavenaskIndexMappingProviderTests.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/create/rest/RestHavenaskCreateTests.java

fix : https://github.com/alibaba/havenask-federation/issues/522

创建索引时增加校验，不允许字段名为"summary"

---

elastic-fed/client/rest-high-level/src/main/java/org/havenask/client/ha/SqlResponse.java
elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/RecoveryIT.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/search/HavenaskSearchFetchProcessor.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/search/dsl/DSLSession.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/search/dsl/plan/DSLExec.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/search/dsl/plan/Executable.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/search/dsl/plan/QueryExec.java
elastic-fed/modules/havenask-engine/src/test/java/org/havenask/engine/search/fetch/HavenaskSearchFetchProcessorTests.java

fix : https://github.com/alibaba/havenask-federation/issues/519

search查询在底层sql查询异常时抛出异常信息而不是返回空结果

---

elastic-fed/modules/havenask-engine/src/javaRestTest/java/org/havenask/engine/SearchIT.java
elastic-fed/modules/havenask-engine/src/main/java/org/havenask/engine/index/config/BizConfig.java

fix : https://github.com/alibaba/havenask-federation/issues/517

优化cluster.json的默认参数
